<?php

namespace app\modules\backend;

use yii\base\Module;

class BackendModule extends Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}