<?php

namespace app\controllers;

use yii\web\Controller;
use yii\web\Response;

class BaseController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->enableCsrfValidation = false;
    }

    protected function success($data = [], $code = 0, $msg = 'success')
    {
        $response = \Yii::$app->response;
        $response->format = Response::FORMAT_JSON;
        $response->data = [
            'code' => $code,
            'message' => $msg,
            'data' => $data
        ];
    }

    protected function error($code = 0, $msg = 'error', $data = []){
        $response = \Yii::$app->response;
        $response->format = Response::FORMAT_JSON;
        $response->data = [
            'code' => $code,
            'message' => $msg,
            'data' => $data
        ];
    }

    protected function queryParam($paramKey, $default)
    {
        if (empty($paramKey)) {
            return $default;
        }

        $cookies = \Yii::$app->request->cookies;
        if (isset($cookies[$paramKey])) {
            return $cookies[$paramKey]->value;
        }
        elseif (\Yii::$app->request->getIsGet()) {
            return \Yii::$app->request->get($paramKey, $default);
        }
        elseif (\Yii::$app->request->getIsPost()) {
            return \Yii::$app->request->post($paramKey, $default);
        }

        return null;
    }

    protected function parseFloat($paramKey, $default)
    {
        return floatval($this->queryParam($paramKey, $default));
    }
}