<?php

namespace app\modules\frontend;

use yii\base\Module;

class FrontendModule extends Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}